// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('d:/Moveable-Personal/Ontegra/licentav1/node_modules/react');
var { Component } = React;
var ReactNative = require('d:/Moveable-Personal/Ontegra/licentav1/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('licentav1', appParameters);
});
require('d:/Moveable-Personal/Ontegra/licentav1/index.js');